# Generated by Django 5.1.2 on 2025-07-04 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categorys', 'verbose_name_plural': 'Categories'},
        ),
    ]
