# Generated by Django 5.1.2 on 2025-07-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categorys', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='file',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
